I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    init python:
  File "game/script.rpy", line 35, in <module>
    sac = Item("sac", sac.jpg)
NameError: name 'sac' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    init python:
  File "C:\Users\game\Desktop\renpy-8.2.0-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\game\Desktop\renpy-8.2.0-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 35, in <module>
    sac = Item("sac", sac.jpg)
NameError: name 'sac' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
visual novel 1.0
Mon Feb  5 16:45:19 2024
